### ISSUE TITLE
A Tool Proposal For Translation Process Management

### ISSUE THREAD

**Issue by umutphp** [github/opensource.guide#1133]
I have contributed translation processes of some projects on Github. After finishing some of them manually, I'm convinced that using a tool to translate is more accurate than doing it manually. I have translated this document to [Turkish](https://github.com/github/opensource.guide/pull/1112) by using [GitLocalize](https://gitlocalize.com/). 

![gitlocalize](https://user-images.githubusercontent.com/3245166/66431047-f06de680-ea23-11e9-9caa-e4b8941dd3e1.gif)

The two main reasons for me to use it;
- Creates text segments from content and manages translation segment based
- Notifies when the master content is updated

As this repository contains many documents and most of the translation requirements comes from the content updates (very rare new content), GitLocalize may be a good choice. It has also team management functions such as language moderators, reviews and discussions.

By the way, I have no connection with this tool :).

**Comment by umutphp** [comment]
Yes, I have used GitLocalize in some of the translation projects that I involved in. I also used it for the Turkish translation of this repo.

Can you please create an account on GitLocalize? So, I can add you to the team of one of my forks.

**Comment by MikeMcQuaid** [comment]
@umutphp Done! If you could add me to your opensource.guide fork that'd be great.

**Comment by umutphp** [comment]
@MikeMcQuaid added you as admin to my fork.

**Comment by umutphp** [comment]
@MikeMcQuaid 
Just circling back on the translation of the guide :). 

Can you please provide me an update about your comments about the tool? Did you have time to check? Do you think it can be used for managing the translation flow of this guide?

**Comment by sschevy74** [comment]
I have an account on github. 

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 9, 2019 at 5:37 AM, Umut Işık<notifications@github.com> wrote:   
Yes, I have used GitLocalize in some of the translation projects that I involved in. I also used it for the Turkish translation of this repo.

Can you please create an account on GitLocalize? So, I can add you to the team of one of my forks.

**Comment by MikeMcQuaid** [comment]
@umutphp I haven't had time to check yet, sorry. This repository is not part of my job at GitHub so I've got stuff here bookmarked to review when I next have some free time (and am working hard on a GitHub Universe ship at the moment). Apologies again!

**Comment by sschevy74** [comment]
No 

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 21, 2019 at 3:28 AM, Umut Işık<notifications@github.com> wrote:   
@MikeMcQuaid
Just circling back on the translation of the guide :).

Can you please provide me an update about your comments about the tool? Did you have time to check? Do you think it can be used for managing the translation flow of this guide?

**Comment by ilyaspiridonov** [comment]
@MikeMcQuaid 
@umutphp 
Hi Mike and Umut, I'm from GitLocalize team, so if you ever need assistance with setting up a project or have any questions feel free to reach out to me directly at ilya@gitlocalize.com

**Comment by MikeMcQuaid** [comment]
@ilyaspiridonov Will do, still planning on getting to this at some point 🤞

**Comment by katrinleinweber** [comment]
I'm curious to try this, but sceptical. Having used several of those tools for UI l18n, but only observed [Transifex.com/carpentries-i18n](https://www.transifex.com/carpentries-i18n/handbook-translations/) I'm a bit sceptical that those tools _also_ work well for free-flowing text. Also, wherever a legal matter is touched, the different translations shouldn't even be too "tightly coupled". Thus, tools that promote such close alignment of translations might even do harm to some topics. 

Is there a positive example for "segment based" translation? Do professional (book) translators use such tools?

**Comment by umutphp** [comment]
Hi @katrinleinweber ,
I agree with your concerns about such possible issues. 

I think the biggest problem with translations of this kind of documents is that they cannot follow updates in the master content. My motivation in creating this issue was to find a way to identify changes in master content as a translator to keep the translation up-to-date.

I do not have any professional or book translations with such tools. I hope there will someone to share experience :).

**Comment by MikeMcQuaid** [comment]
I'm sorry that it's taken so long for me to properly look at this but unfortunately I'm getting an "application error" every time I try to create a new repository here: https://gitlocalize.com/repo/new

As a result I'm not (yet) confident that we can begin a move over to using this tool CC @ilyaspiridonov @umutphp. I'm open to other tools and taking a look again when these issues are addressed.

**Comment by ilyaspiridonov** [comment]
@MikeMcQuaid Mike, you might have caught a moment where we were rolling out an update, sorry about that. Should be working fine now - can you please give it another try?

**Comment by MikeMcQuaid** [comment]
@ilyaspiridonov I'm still seeing "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command" every time I visit https://gitlocalize.com/repo/new.

**Comment by ilyaspiridonov** [comment]
@MikeMcQuaid thanks, I’ve just finished an urgent session with our dev team and I think we found the reason. Looks like you have quite a few repositories (1000+ I’m being told ), and Gitlocalize is hitting GitHub’s API rate limit and our memory quotas while trying to process the list of repos - that’s why you can’t even see the Add Repo screen. Obviously, our logic is not optimized for that kind of use case, and we are now working on a solution.
On the other hand, it was a great test case, so thanks! )
I will update once we find a solution, but should you have a second, more “lightweight” GitHub account, please feel free to try adding a repo from that account.
Sorry for the inconvenience, we’re doing our best to make GitLocalize better.

**Comment by MikeMcQuaid** [comment]
@ilyaspiridonov My personal account and organisations I'm administrators of have relatively small numbers of repositories but I have read access to >1000 private repositories for sure.

> I will update once we find a solution, but should you have a second, more “lightweight” GitHub account, please feel free to try adding a repo from that account.

I'm afraid I don't have any I could use, sorry. I'd need to be the one that could set this up so I'm sorry but we'll need to pass on GitLocalize for now (a shame as it looks like a wonderful too).

Give me a shout or post in this issue when you reckon it's ready for testing again and we can consider reopening.

Thanks again!
